### ISSUE TITLE
Add packageRoot on configuration

### ISSUE THREAD

**Issue by pith** [nuun-io/kernel#59]
Add a `packageRoot(String...)` method on `KernelConfiguration`. It will be easier to discover than with the curent `param()` method.

Also add a warn when no packageRoot is specified.

```
========================== WARNING ==========================
Please update your application package root inside 
     → /META-INF/resources/nuun.conf
with 
     →  nuun.package.root = com.acme1, com.acme2

You're actually scanning the WHOLE classpath 
========================== WARNING ==========================
```

See #58 for previous discussion.

**Comment by pith** [comment]
A new param `param("scan.warn.disable", true)` (false by default) should be added.

**Comment by ejemba** [comment]
- We should also show the programmatic solution in the warning.
- Yes the `scan.warn.disable` should be introduced. 
- in KernelConfiguration the method should be named `rootPackage(String ...)` rather than   `packageRoot(String...)` 
- In `Plugin` interface, the name of the method `String pluginPackageRoot();`
 should be in fact `String pluginRootPackage();` in order to clean this feature everywhere in the code, if you see others you can fix them the correct form is `rootPackage` 

The warning message should be updated like this 
```
================================ WARNING ================================
   You're actually scanning the WHOLE classpath , this can be time consuming.
   Please update your application configuration, to narrow the scan to your application.
   
 1) You can update /nuun.conf in the classpath with the following content

          rootPackage = com.acme1, com.acme2
   
   where com.acme1 and com.acme2 are your root packages.
   
 2) You can programmatically use KernelConfiguration.rootPackage("com.acme1" , "com.acme2")

   Same as above

 3) You can programmatically use KernelConfiguration.param("scan.warn.disable" , "true")

   This will disable the warning. It implies, you know what you are doing.

========================================================================
```

**Comment by pith** [comment]
So you want to deprecate the `pluginPackageRoot()` method ?

**Comment by ejemba** [comment]
Yes deprecate it in order to have the clean api for the 1.0.
Yes `rootPackages()` is better.

**Comment by pith** [comment]
Ok I started a branch: https://github.com/nuun-io/kernel/tree/fix-59-rootPackages
